// GENERATED FILE - DO NOT EDIT BY HAND.
//
// Generated by RokctAI/shared-workflows scripts/tour/merge_fragments.py from
// this app's tour/app.tour.yaml plus the tour fragments shipped by the
// composed SDKs (each SDK's templates/tour/<sdk>.tour.yaml). CI regenerates
// it on every guided-tour run; the committed copy exists so the repo
// analyzes and compiles without running the merge first.
//
// ignore_for_file: unused_import, always_specify_types, avoid_redundant_argument_values
// ignore_for_file: unawaited_futures, use_build_context_synchronously
// ignore_for_file: implementation_imports, directives_ordering, depend_on_referenced_packages

import 'package:auto_route/auto_route.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:auth_sdk/src/common/application/auth/auth.dart';
import 'package:base_sdk/src/models/data/address_old_data.dart';
import 'package:base_sdk/src/models/data/location.dart';
import 'package:base_sdk/src/models/response/languages_response.dart';
import 'package:base_sdk/src/presentation/pages/profile/generic_profile_page.dart' as base_profile;
import 'package:base_sdk/src/services/app_helpers.dart';
import 'package:base_sdk/src/services/local_storage.dart';
import 'package:base_sdk/src/services/tr_keys.dart';
import 'package:comms_sdk/src/common/presentation/pages/setting/language_page.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:marketplace_sdk/src/common/presentation/pages/home/home_zero/filter/result_filter.dart' as marketplace_filter;
import 'package:marketplace_sdk/src/common/presentation/pages/home/home_zero/home_page.dart' as marketplace_home;
import 'package:marketplace_sdk/src/common/presentation/pages/like/like_page.dart' as marketplace_like;
import 'package:marketplace_sdk/src/common/presentation/pages/search/search_page.dart' as marketplace_search;

typedef TourAction = Future<void> Function(
    WidgetTester tester, StackRouter router);

class TourStep {
  const TourStep(this.key, this.settleMs, this.screenshot, this.action);

  final String key;
  final int settleMs;

  /// False for steps that only perform an action (no still captured).
  final bool screenshot;
  final TourAction action;
}

/// Runs once before the app is launched.
Future<void> tourSetup() async {
  // Pre-seed the language so the first-run language picker can never
  // block the tour behind a non-dismissible modal (the backend may
  // advertise several languages). LocalStorage.init() is idempotent -
  // app.main() calls it again.
  await LocalStorage.init();
  if (LocalStorage.getLanguage() == null) {
    await LocalStorage.setLanguageData(LanguageData(
      id: '1',
      title: 'English',
      locale: 'en',
      backward: false,
      isDefault: true,
      active: true,
    ));
    await LocalStorage.setLanguageSelected(true);
    await LocalStorage.setLangLtr(false);
  }
}

final List<TourStep> tourSteps = <TourStep>[
  TourStep('welcome', 12000, true, (WidgetTester tester, StackRouter router) async {
    // wait: settle only.
  }),
  TourStep('auth_login', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Land on /login (the welcome screen), then open the login sheet the
    // way a user does - via its Login button.
    router.replaceNamed('/login');
    await Future<void>.delayed(const Duration(seconds: 3));
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.login)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_register', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Close the login sheet, then open the register sheet from the
    // welcome screen's Register button.
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    if (navigator.canPop()) {
      navigator.pop();
      await Future<void>.delayed(const Duration(seconds: 2));
    }
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.register)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_reset_password', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Close the register sheet, reopen the login sheet, then tap
    // "Forgot password" - its handler swaps the login sheet for the
    // reset-password sheet, exactly the path a user takes.
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    if (navigator.canPop()) {
      navigator.pop();
      await Future<void>.delayed(const Duration(seconds: 2));
    }
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.login)).first,
      warnIfMissed: false,
    );
    await Future<void>.delayed(const Duration(seconds: 3));
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.forgotPassword)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_back_to_login', 3000, false, (WidgetTester tester, StackRouter router) async {
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    // Bounded: at most one sheet is open, but stay safe against strays.
    for (int i = 0; i < 5 && navigator.canPop(); i++) {
      navigator.pop();
      await Future<void>.delayed(const Duration(milliseconds: 500));
    }
    router.replaceNamed('/login');
  }),
  TourStep('demo_sign_in', 6000, false, (WidgetTester tester, StackRouter router) async {
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    // loginProvider is autoDispose: hold a subscription so the notifier
    // survives between the field writes and the login call.
    final ProviderSubscription<dynamic> subscription =
        container.listen(loginProvider, (_, __) {});
    try {
      final login = container.read(loginProvider.notifier);
      login.setEmail('demo.student@example.com');
      login.setPassword('demo-learners-2026');
      // MockAuthRepository accepts any credentials. The timeout guards the
      // post-session FCM sync, which can stall on an emulator - navigation
      // to the demo landing happens before it, so a timeout is harmless.
      await login
          .login(element)
          .timeout(const Duration(seconds: 45), onTimeout: () {});
    } finally {
      subscription.close();
    }
  }),
  TourStep('marketplace_home', 10000, true, (WidgetTester tester, StackRouter router) async {
    // Seed the demo session state the customer screens key off:
    //  - a selected address, so home's checkAddress() does not cover the
    //    screen with the AddAddress dialog on a fresh install;
    //  - one saved shop id ("1" = MockShopsRepository's Demo Shop), so
    //    the favourites step later shows a stocked list.
    await LocalStorage.setAddressSelected(AddressData(
      id: 1,
      title: 'Demo address',
      address: '1 Demo Street',
      location: LocationModel(latitude: -26.2041, longitude: 28.0473),
    ));
    await LocalStorage.setSavedShopsList(<String>['1']);
    // marketplace_sdk declares no customer routes yet, so push its own
    // page directly (see the header note); the pushed page inherits the
    // app's ProviderScope, theme and localization.
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    navigator.push(MaterialPageRoute<void>(
      builder: (_) => const marketplace_home.HomePage(),
    ));
  }),
  TourStep('marketplace_category', 8000, true, (WidgetTester tester, StackRouter router) async {
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    // Bounded: pop the page the previous step pushed.
    for (int i = 0; i < 3 && navigator.canPop(); i++) {
      navigator.pop();
      await Future<void>.delayed(const Duration(milliseconds: 500));
    }
    // Category id "1" is MockCategoriesRepository's demo "Burgers"
    // category; the shop list comes from MockShopsRepository.
    navigator.push(MaterialPageRoute<void>(
      builder: (_) =>
          const marketplace_filter.ResultFilterPage(categoryId: '1'),
    ));
  }),
  TourStep('marketplace_search', 8000, true, (WidgetTester tester, StackRouter router) async {
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    for (int i = 0; i < 3 && navigator.canPop(); i++) {
      navigator.pop();
      await Future<void>.delayed(const Duration(milliseconds: 500));
    }
    navigator.push(MaterialPageRoute<void>(
      builder: (_) => const marketplace_search.SearchPage(),
    ));
  }),
  TourStep('marketplace_favourites', 8000, true, (WidgetTester tester, StackRouter router) async {
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    for (int i = 0; i < 3 && navigator.canPop(); i++) {
      navigator.pop();
      await Future<void>.delayed(const Duration(milliseconds: 500));
    }
    // Renders the saved shop seeded in the first step via
    // MockShopsRepository.getShopsByIds.
    navigator.push(MaterialPageRoute<void>(
      builder: (_) => const marketplace_like.LikePage(),
    ));
  }),
  TourStep('marketplace_profile', 8000, true, (WidgetTester tester, StackRouter router) async {
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    for (int i = 0; i < 3 && navigator.canPop(); i++) {
      navigator.pop();
      await Future<void>.delayed(const Duration(milliseconds: 500));
    }
    // The account screen is base_sdk's generic profile host, composed
    // from the sections marketplace_sdk registered at boot (its
    // manifest's marketplace-profile-sections di hook) - the same page
    // the /profile route shows since the GenericProfilePage migration.
    // Without a token the profile fetches are guarded and the page
    // renders its guest state - truthful for a signed-out browser.
    navigator.push(MaterialPageRoute<void>(
      builder: (_) => const base_profile.GenericProfilePage(),
    ));
  }),
  TourStep('comms_language', 6000, true, (WidgetTester tester, StackRouter router) async {
    // Open the language sheet the way the app's own screens do: the same
    // AppHelpers.showCustomModalBottomSheet call auth's login page and
    // marketplace's profile use for EmbeddedWidgets.I.languageScreen.
    // LanguageScreen is comms_sdk's own widget; in demo builds its list
    // comes from MockSettingsRepository.getLanguages().
    final BuildContext sheetContext =
        tester.element(find.byType(Navigator).first);
    AppHelpers.showCustomModalBottomSheet(
      context: sheetContext,
      modal: LanguageScreen(
        onSave: () =>
            Navigator.of(sheetContext, rootNavigator: true).pop(),
      ),
      isDarkMode: false,
    );
  }),
  TourStep('comms_language_close', 3000, false, (WidgetTester tester, StackRouter router) async {
    // Tolerant: pop only when the sheet from the step above is actually
    // on screen, so this can never pop a real app route.
    if (find.byType(LanguageScreen).evaluate().isNotEmpty) {
      final NavigatorState navigator =
          tester.state(find.byType(Navigator).first);
      if (navigator.canPop()) {
        navigator.pop();
      }
    }
  }),
  TourStep('wallet_topup', 7000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/wallet-topup');
  }),
  TourStep('wallet_history', 7000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/wallet-history');
  }),
];
